export default [
  { "word": "Egg" },
  { "word": "Person" },
  { "word": "Car" },
  { "word": "Balloon" },
  { "word": "Keys" },
  { "word": "Money" },
  { "word": "Camera" },
  { "word": "Clock" },
  { "word": "Headphones" },
  { "word": "Watch" },
  { "word": "Router" },
  { "word": "Cup" },
  { "word": "Toothbrush" },
  { "word": "Pen" },
  { "word": "Dog" },
  { "word": "Ring" },
  { "word": "Wallet" },
  { "word": "Food" },
  { "word": "Hose" },
  { "word": "Broccoli" },
  { "word": "Tissue" },
  { "word": "Lotion" },
  { "word": "Shoe" },
  { "word": "Spoon" },
  { "word": "Cat" },
  { "word": "Deodorant" },
  { "word": "Controller" },
  { "word": "Book" },
  { "word": "Refridgerator" },
  { "word": "Toilet" },
  { "word": "Purse" },
  { "word": "Cookie" },
  { "word": "Piano" },
  { "word": "Flower" },
  { "word": "Hanger" },
  { "word": "Stop Sign" },
  { "word": "Playing Card" },
  { "word": "Hair Brush" },
  { "word": "Cloud" },
  { "word": "Tree" },
  { "word": "Thermostat" },
  { "word": "Glasses" },
  { "word": "Lamp" },
  { "word": "Ice" },
  { "word": "Meat" },
  { "word": "Pillow" },
  { "word": "Charger" },
  { "word": "Washing Machine" },
  { "word": "Sunglasses" }

]